nt(getattr(s,"name"))
# method=getattr(s,"greet")
# print(method)
# print(method())
# method1=getattr(s,"name")
# print(callable(method1))
# method2=getattr(s,"greet")
# print(callable(method2))
# print(method2())
# method3=getattr(s,"age","notfound")
# print(method3)
# method4=getattr(s,"name","notfound")
# print(method4)
# setattr(s,"age",20)
# print(getattr(s,"age"))
# print(s.age)